metadb can now handle request/reply
mskcc/cmo-metadb pull request #323
Opened 2021-07-08 13:19 UTC by divyamadala30

Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>

2021-07-08 13:21 UTC, divyamadala30 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +}
Need to add an extra line here

2021-07-08 18:19 UTC, ao508 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +    @Value("${request_reply.patient_samples_topic}")
don't forget to add this new prop to the example properties

2021-07-08 20:08 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +                        System.out.println("Publishing to: " + replyInfo.getReplyTo() + "\n message: "+ replyInfo.getReplyMessage());
Lets get rid of this output.  If we want it, we should put into a log file.

2021-07-08 20:23 UTC, n1zea144 requested changes

2021-07-08 20:23 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +public class RequestReplyHandlingServiceImpl implements RequestReplyHandlingService {
Is the idea that this class will contain all request-reply handlers and MessagingHandlingService will contain all other handlers?

2021-07-08 20:23 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +    private String REQUEST_REPLY_TOPIC;
Suggest this be called something more specific to the actual topic in the event a new request-reply topic is introduced in the future.

2021-07-08 20:23 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +                        System.out.println("Publishing to: " + replyInfo.getReplyTo() + "\n message: "+ replyInfo.getReplyMessage());
Lets get rid of the output to stdout. If we want it, we should put into a log file.

2021-07-08 20:23 UTC, n1zea144 commented on service/src/main/java/org/mskcc/cmo/metadb/service/impl/RequestReplyHandlingServiceImpl.java
> +            List<SampleMetadata> sampleList = sampleService.getSampleMetadataListByCmoPatientId(patientId);
I would move this into NewRequestReplyHandler.run() so we don't tie up the message handling thread.

2021-07-14 18:53 UTC, n1zea144 approved these changes

2021-07-14 19:58 UTC, merged