PublishSampleMetadata updates
mskcc/cmo-metadb pull request #523
Opened 2021-12-20 20:27 UTC by divyamadala30

Briefly describe changes proposed in this pull request:
- MetadbSample now has field `datasource`
- `datasource` is populated in sampleDataFactory
- PubblishedSampleMetadata now returns `datasource` and `Patient` with `PatientAlias`

### Screenshots
Patient added to the returned sample JSON:

<img width="719" alt="Screen Shot 2021-12-20 at 2 54 45 PM" src="https://user-images.githubusercontent.com/71040191/146828109-a5e561d3-fbf5-4481-b694-7d442e267bc6.png">

MetaDbSample node has populates field `datasource`:

<img width="834" alt="Screen Shot 2021-12-20 at 2 54 56 PM" src="https://user-images.githubusercontent.com/71040191/146828232-36514157-4f08-4a25-9e80-5dbb9e454404.png">

## Crossing T's and dotting I's

Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more information.

### Web service and data model checklist

Please follow these checks if any changes were made to any classes in the web, service, or persistence layers.
- [x] Have the endpoints been tested to ensure they have not broken from the changes introduced?
- [x] Have screenshots been uploaded to demonstrate changes made to the response body JSON schema and/or swagger page?
- [x] Were updates made to the mocked incoming request data and/or mocked published request data?
  - [x] [cmo-metadb test data](https://github.com/mskcc/cmo-metadb/tree/master/service/src/test/resources/data)
  - [x] [cmo-metadb-common test data](https://github.com/mskcc/cmo-metadb-common/tree/master/src/test/resources/data)
- ~[ ] Have unit tests been updated in relation to updates to the mocked test data?~

### Neo4j models and database schema checklist:
- [x] Were any of the neo4j persistence models changed?
- [x] Does the graph database produce the expected changes to models, relationships, and/or property names? [provide screenshot of updated elements in graph db]

### Message handlers checklist:
- ~[ ] Were changes introduced in this PR that may affect the workflow of incoming messages?~
- ~[ ] Are messages following the expected workflow when published to the topic(s) changed in this pull request?~
- ~[ ] Were unit tests added to ensure messages are handled as expected?~

If no unit tests were updated or added, then please explain why: Current units tests cover the added fields

Please describe how the workflow and messaging was tested/simulated:

**Your environment**

- NATS [**local**, local docker, dev server, production]
- Neo4j [**local**, local docker, dev server, production]
- MetaDB [**local**, local docker, dev server, production]
- Message publishing simulation [nats cli, docker nats cli, **metadb publisher tool**, other (describe below)]

### General checklist:
- [x] Have tests or has a separate issue that describes the types of tests that should be created been linked or created? If no test is included it should explicitly be mentioned in the PR why there is no test.
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)

Signed-off-by: Divya Madala 71040191+divyamadala30@users.noreply.github.com

2021-12-20 20:32 UTC, ao508 requested changes

2021-12-20 20:32 UTC, ao508 commented on service/src/main/java/org/mskcc/cmo/metadb/service/util/SampleDataFactory.java
> +        sample.setDatasource("research");
this should be `igo` for datasource, other than that the pr looks good!

2021-12-20 20:33 UTC, ao508 requested changes

2021-12-20 20:33 UTC, ao508 commented on model/src/main/java/org/mskcc/cmo/metadb/model/web/PublishedMetadbSample.java
> +    public MetadbPatient getPatient() {
actually I realize another thing - `patientAliases` only should be added to the published sample

2021-12-20 20:36 UTC, ao508 commented on model/src/main/java/org/mskcc/cmo/metadb/model/web/PublishedMetadbSample.java
> +    public MetadbPatient getPatient() {
another thing regarding `patientAliases` - we should add `@JsonIgnore` to the Patient Metadata // where is that coming from?

2021-12-20 20:39 UTC, ao508 commented on model/src/main/java/org/mskcc/cmo/metadb/model/web/PublishedMetadbSample.java
> +    public MetadbPatient getPatient() {
this is a screen shot of what the mocked published data looks like / what we should have the web service return for the `sampleAliases` and `patientAliases` contents

![image](https://user-images.githubusercontent.com/15623749/146829795-11e43d88-67c9-4d41-ae10-45d80c482f76.png)

2021-12-20 20:49 UTC, divyamadala30 commented
New model for PatientAlias in requestJson:

<img width="499" alt="Screen Shot 2021-12-20 at 3 45 52 PM" src="https://user-images.githubusercontent.com/71040191/146830851-50e1878e-6f7c-46fa-b983-51657e5c5cff.png">

2021-12-21 14:42 UTC, ao508 approved these changes

2021-12-21 14:43 UTC, merged